### PR TITLE
🚑 Don't add "db down" rule if no Postgresql

### PR DESCRIPTION
**Pull request by grdryn**
JIRA: https://issues.redhat.com/browse/INTLY-4497

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
👀

**Comment by laurafitzgerald** [comment]
**Verification**
_With Internal Posgresql_
`make install`
UnifiedPushDatabaseDown rule is present in the Prometheus Rule

_With Exteranal postgresql_
`oc apply -f deploy/crds/push_v1alpha1_unifiedpushserver_cr_with_external_db.yaml`

UnifiedPushDatabaseDown rule is not present

/approve

**Review by laurafitzgerald — APPROVED** [review]
Verified changes work as expected. I noticed there's no documentation about the use of external postgres in the README. Maybe that's fine. We do document the values accepted by the UnifiedPushServer cr. I'll leave that one with you.

**Comment by grdryn** [comment]
Thanks for the review @laurafitzgerald!

> Verified changes work as expected. I noticed there's no documentation about the use of external postgres in the README. Maybe that's fine. We do document the values accepted by the UnifiedPushServer cr. I'll leave that one with you.

Good point, I'll make a comment of that in https://issues.redhat.com/browse/INTLY-4379 and try to cover it in that (otherwise that might require a change there anyway)

**Pull request merged**
