### PR TITLE
Fix alert removed in openshift 4.7.12

### PR DESCRIPTION
**Pull request by CathalOConnorRH**
## Motivation
Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: https://issues.jboss.org/browse/AEROGEAR-{} AND/OR ISSUE: https://github.com/aerogear/standards/issues/{}) 

## What
Add an short answer for: What was done in this PR? (E.g Don't allow users has access to the feature X.)

## Why
Add a short answer for why was it done (E.g The feature X was deprecated.)

## How
Add an short answer for: How it was done? (E.g By removing this feature from ... OR By removing just the button but not its implementation ... ) 

## Verification Steps
Add the steps required to check this change. Following an example.
 
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task
- [ ] TODO

## Additional Notes

PS.: Add images and/or .gifs to illustrate what was changed if this pull request modifies the appearance/output of something presented to the users.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
Verified by @matskiv we can merge this when the build is completed.
@secondsun I think that's probably pending for a while. Do you know how to retrigger it?

**Comment by psturc** [comment]
@laurafitzgerald that Jenkins instance is dead. I don't think we'll be able to retrigger the check.

I'd say if changes in this PR were verified, let's create a release with a new pipeline.

**Comment by matskiv** [comment]
I've seen this PR deployed on a cluster on Fri, and alert looked as expected.
Merging :)

**Comment by matskiv** [comment]
@psturc btw: we need a PR with version bump before creating a release. AFAIK Patryk is looking into that.

**Pull request merged**
