### PR TITLE
chore: update backup-container to 1.0.16

### PR DESCRIPTION
**Pull request by wei-lee**
## Motivation
https://issues.redhat.com/browse/INTLY-10332

## What
Update the backup-container to the latest version

### CODE REVIEW

**Review by austincunningham — APPROVED** [review]
/lgtm
/approve

**Comment by wei-lee** [comment]
@secondsun can you please take a look at the PR? The pr-merge check failed, I tried to restart it on Jenkins but that doesn't work. also not sure why it is failed.

**Comment by psturc** [comment]
@wei-lee I looked at the jenkins job and there was e2e test failing, because it couldn't spin up UPS.
The reason was that postgresql image couldn't be pulled:
```
Failed to pull image "centos/postgresql-10-centos7:1": rpc error: code = Unknown desc = toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

([Docker has introduced rate limits for image pull requests on November 2020](https://access.redhat.com/solutions/5603421))

I provisioned a new slave for Jenkins and rebuilt the job. This time `continuous-integration/jenkins/pr-merge` has passed. However when I reran `continuous-integration/jenkins/branch` so it could also pass, I received  `toomanyrequests` error again and provisioning a new slave didn't work this time (got the same error).

So `continuous-integration/jenkins/pr-merge` has passed, and **I think it's safe to merge this PR** (because `continuous-integration/jenkins/branch` runs the same tests against the same branch).
But I was wondering - since pulling the images from `docker.io` could be problematic now due to rate limit on pulls, would it make sense to use an image from different container image registry (i.e. quay.io, registry.redhat.io)?

**Update**
On second try (after couple of hours) the other test job also has passed.

**Review by jessesarn — APPROVED** [review]

**Comment by jessesarn** [comment]
@secondsun Your help to merge this would be much appreciated.

**Pull request merged**
