### PR TITLE
Fix reconcile to find ImageStream correctly

### PR DESCRIPTION
**Pull request by grdryn**
As discussed [here](https://github.com/aerogear/unifiedpush-operator/pull/28/files/aba55be0568fa2c8c2d7a9a301596f410a5c0f0d#r297605646).

### CODE REVIEW

**Comment by aliok** [comment]
Verified. I don't see that particular error anymore.

I see this though:
```
{"level":"error","ts":1561639160.1588542,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"unifiedpushserver-controller","request":"unifiedpush/example-unifiedpushserver","error":"routes.route.openshift.io \"example-unifiedpushserver-unifiedpush-proxy\" already exists","stacktrace":"github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/aliok/go/src/github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/aliok/go/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/aliok/go/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/aliok/go/src/github.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/aliok/go/src/github.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/aliok/go/src/github.com/aerogear/unifiedpush-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

But it is not the fixed case.

@odra any experience with the error above?

**Review by aliok — APPROVED** [review]

**Comment by odra** [comment]
it means that a route with that name (example-unifiedpushserver-unifiedpush-proxy) already exists in the namespace, any change you already have one?

**Comment by aliok** [comment]
> it means that a route with that name (example-unifiedpushserver-unifiedpush-proxy) already exists in the namespace

Yeah but why that happens is what I meant to ask.

**Comment by odra** [comment]
any change you creating it twice in the controller loop?

**Comment by grdryn** [comment]
I see that _sometimes_, and similarly for the other openshift-specific kinds. I guess they might be handled slightly differently in their library than the kubernetes ones or something? I don't think I've seen it for any kubernetes kinds. It does seem a bit racy, but at the same time innocuous, so I haven't looked into it in any depth.

**Comment by odra** [comment]
I never saw that error in my operators (randomly), might be some data racing in the loop itself.

**Comment by aliok** [comment]
Yes.

@grdryn Feel free to merge this one!

**Pull request merged**
