### PR TITLE
feat: extend e2e test - verify UPS deployment

### PR DESCRIPTION
**Pull request by psturc**
## Motivation
https://issues.jboss.org/browse/AEROGEAR-9592

## What
Test verifying that UPS can be deployed successfully

## Verification Steps
See the result of Jenkins job

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

### CODE REVIEW

**Review by grdryn — COMMENTED** [review]
LGTM.

@psturc When we add more resources that get created on reaction to a UPS CR, should we check for those in the e2e test also?

**Review by grdryn — APPROVED** [review]

**Comment by psturc** [comment]
@grdryn if it's possible to check within a test if app or variant gets successfully created, I think it makes sense to add such test.

Currently, tests are failing after AMQ stuff [got merged](https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/unifiedpush-operator/job/master/15/). Is that because we're expecting AMQ service to be present on a cluster?

Here are the logs from unifiedpush-operator that's in a `CrashLoopBackOff` status (reason why tests are failing).
<details>
{"level":"error","ts":1563436576.8412545,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MessagingUser.user.enmasse.io","error":"no matches for kind \"MessagingUser\" in version \"user.enmasse.io/v1beta1\"","stacktrace":"github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver.add\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver/unifiedpushserver_controller.go:135\ngithub.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver.Add\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/pkg/controller/unifiedpushserver/unifiedpushserver_controller.go:40\ngithub.com/aerogear/unifiedpush-operator/pkg/controller.AddToManager\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/pkg/controller/controller.go:13\nmain.main\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/cmd/manager/main.go:139\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
{"level":"error","ts":1563436576.841347,"logger":"cmd","msg":"","error":"no matches for kind \"MessagingUser\" in version \"user.enmasse.io/v1beta1\"","stacktrace":"github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/home/jenkins/workspace/unifiedpush-operator_PR-48-VW5RU4NHTZXKXYP4HATV3WCK2HPBUJCI3PQKAVAGRBHAKHJIUKSQ/src/github.com/aerogear/unifiedpush-operator/cmd/manager/main.go:140\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
</details>

**Comment by grdryn** [comment]
Argh, I think it's maybe because the controller adds watches for those kinds now, even if the `useMessageBroker` flag is set to false in the CRD. I'm curious how the job passed in #31 in that case though :thinking: 

@secondsun @wei-lee maybe it would be better if that `useMessageBroker` boolean was an env var to the operator rather than a field in the CR spec? That way we could conditionally add the watches only if it's set (assuming that's the problem here). Having it as a field in the CR additionally opens us up to people thinking they can change it after initial creation, which is at least "untested".

**Comment by grdryn** [comment]
I've created #49 which should work around this issue for now.

**Comment by psturc** [comment]
I will add app & variant creation test in a separate PR.

**Pull request merged**
